app:
  mode: test
  port: 8088

mysql:
  master:
    dsn: root:root@tcp(127.0.0.1:3306)/jin_cheng?charset=utf8&parseTime=True&loc=Local
  slave:
    dsn: root:root@tcp(127.0.0.1:3306)/jin_cheng?charset=utf8&parseTime=True&loc=Local
  driver: mysql
  prefix: jc_

jwt:
  alg: HS256
  issuer: scott
  expiresAt: 24h
  secret: jc_scott