app:
  mode: test
  port: 8088

mysql:
  master:
    dsn: root:root@tcp(192.168.128.1:3306)/jin_cheng?charset=utf8&parseTime=True&loc=Local
  slave:
    dsn: root:root@tcp(192.168.128.1:3306)/jin_cheng?charset=utf8&parseTime=True&loc=Local
  driver: mysql
  prefix: jc_