app:
  port: 8080

mysql:
  master:
    dsn: root:root@tcp(127.0.0.1:3306)/zlb_pre?charset=utf8&parseTime=True&loc=Local
  slave:
    dsn: root:root@tcp(127.0.0.1:3306)/zlb?charset=utf8&parseTime=True&loc=Local
  driver: mysql