// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/sirupsen/logrus"
	"study_wire/config"
	"study_wire/internal/core/log"
	"study_wire/internal/db"
)

// Injectors from wire.go:

func InitApp() App {
	configConfig := config.GetConfig()
	logger := log.NewLog()
	dataBase := db.NewDataBase(configConfig, logger)
	app := App{
		DataBase: dataBase,
		Config:   configConfig,
		Logger:   logger,
	}
	return app
}

// wire.go:

type App struct {
	DataBase db.DataBase    `json:"data_base"`
	Config   config.Config  `json:"config"`
	Logger   *logrus.Logger `json:"logger"`
}
